name: ai_assistant
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+2

# dart sdk版本
environment:
  sdk: ^3.7.0

dependencies:
  flutter:  # 依赖flutter框架
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # 其他依赖包
  cupertino_icons: ^1.0.8  # 一种风格化图标库
  provider: ^6.1.1  # 状态管理库，实现数据共享
  shared_preferences: ^2.5.2  # 轻量级本地存储，用于保存键值对
  device_info_plus: ^10.1.2   # 用户获取设备信息的库
  crypto: ^3.0.3   # 加密算法库
  uuid: ^4.5.1  # 创建uuid的库
  timeago: ^3.6.1  # 时间戳处理库
  http: ^1.2.0  # http get/post 请求库
  http_parser: ^4.0.2  # http解析库
  web_socket_channel: ^2.4.0  # websocket管理库
  intl: ^0.19.0  # 国际化库
  image_picker: ^1.2.0  # 从相册/相机 选择图片/视频
  fl_chart: ^0.66.2  # 可视化，绘图库
  get: ^4.7.2  # get风格库
  jwt_decoder: ^2.0.1  # jwt解析库
  flutter_secure_storage: ^9.2.4 # token安全存储库
  dio: ^5.9.0 # 一个更好用的http请求库
  flutter_easyloading: ^3.0.5  # 一个消息弹窗库
  cached_network_image: ^3.4.1  # 一个图片缓存库
  dart_mock: ^2.0.1  # app端 假数据mock工具
  flutter_launcher_icons: ^0.14.4  # app图标自动制作
  flutter_native_splash: ^2.4.6 # 启动图片控制工具
  launcher_name: ^1.0.2  # 控制app的名称

  
  
  # 音频处理相关库
  opus_flutter: ^3.0.3
  opus_dart: ^3.0.1
  flutter_sound: ^9.26.0
  permission_handler: ^11.4.0
  path_provider: ^2.1.5
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  flutter_pcm_player: ^0.0.1
  record: ^5.2.1
  flutter_displaymode: ^0.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^4.0.0
  flutter_blue_plus: ^1.35.3
  audio_streamer: ^4.1.1
  
dev_dependencies:  # 额外的开发依赖，仅仅在开发阶段用，正式打包，不会打包进app
  flutter_test:
    sdk: flutter

  # 官方推荐的代码检查规范，配合 analysis_options.yaml 使用，帮助写出更高质量的 Dart 代码
  flutter_lints: ^5.0.0  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

launcher_name:
  default: "小狮陪伴"

flutter_native_splash:
  # 启动背景色（可选）
  color: "#FFFFFF"

  # 启动图片（关键！）
  image: "assets/icon/pixnio.png"
  android_gravity: fill


  # Android 设置
  android_12:
    image: "assets/icon/pixnio.png"
    color: "#FFFFFF"

  # iOS 设置,这个需要再xcode中进行简单的设置

# 配置应用图标
flutter_launcher_icons:
  image_path: "assets/icon/pixnio.jpg"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/icon/pixnio.jpg" # 透明背景，仅图标主体
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    icon_size: 48
  macos:
    generate: true

# The following section is specific to Flutter packages.
flutter:

  # 启用 Material Design 图标字体
  uses-material-design: true
